[config.wallpaper]
command = "swww"
arguments = ["img" ,"--transition-type" ,"grow" ,"--transition-pos" ,"top-right" ,"--transition-step", "90" ,"--transition-fps" ,"160"]
set = true


[templates.hyprland]
input_path = './templates/hypr.css'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.kitty]
input_path = './templates/kitty.css'
output_path = '~/.config/kitty/colors.conf'
post_hook = "kitty @ set-colors -a -c ~/.config/kitty/colors.conf"

[templates.wofi]
input_path = './templates/wofi.css'
output_path = '~/.config/wofi/style.css'

[templates.define-color]
input_path = './templates/define-color.css'
output_path = '~/.cache/define-color.css'
post_hook = 'pkill -SIGUSR2 waybar && swaync-client -rs && swaync-client --reload-config'
